default:
	gcc -o newfile newfile.c
	gcc -o filedesc filedesc.c
	gcc -o file_rdwr file_rdwr.c
	gcc -o file_rdwr2 file_rdwr2.c
	gcc -o mycp mycp.c
	gcc -o file_offset file_offset.c
	gcc -o dup1 dup1.c
	gcc -o dup2 dup2.c
	gcc -o fcntlex fcntlex.c

clean:
	rm newfile filedesc file_rdwr file_rdwr2 mycp file_offset dup1 dup2 fcntlex

newfile: newfile.c
filedesc: filedesc.c
file_rdwr: file_rdwr.c
file_rdwr2: file_rdwr2.c
mycp: mycp.c
file_offset: file_offset.c
dup1: dup1.c
dup2: dup2.c
fcntlex: fcntlex.c
