default:
	gcc -o dir_access2 dir_access2.c
	gcc -o dir_access dir_access.c
	gcc -o findfile findfile.c
	gcc -o printalpha printalpha.c
	gcc -o printdir printdir.c
clean:
	rm dir_access2 dir_access findfile printalpha printdir 
