default:
	gcc -o prc_runtime prc_runtime.c
	gcc -o sid sid.c
	gcc -o excl_wc excl_wc.c
	gcc -o exec exec.c
	gcc -o exec_dig exec_dig.c
	gcc -o exec_src exec_src.c
	gcc -o ex_sub ex_sub.c
	gcc -o fork_exec fork_exec.c
	gcc -o fork_exit fork_exit.c
	gcc -o fork_prac fork_prac.c
	gcc -o fork_prac2 fork_prac2.c
	gcc -o vfork vfork.c
	gcc -o vfork2 vfork2.c
	gcc -o wait wait.c
	gcc -o wait_pid wait_pid.c
	gcc -o envex envex.c
	gcc -o envex_sub envex_sub.c
	gcc -o mmap mmap.c
clean:
	rm excl_wc exec exec_dig exec_src ex_sub fork_exec fork_exit fork_prac fork_prac2 vfork vfork2 wait wait_pid envex envex_sub sid prc_runtime mmap
