#!/bin/bash
SRC_LIST=`ls | grep "\.c$" | awk -F. '{print $1}'`
F_MAKE=Makefile
DATA=tmp.dat

echo -n "" > $F_MAKE

if [ "$1" = "sql" ]
then
	echo "CFLAGS= -I/usr/include/mysql" >> $F_MAKE
	echo "LIBS= -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -latomic -ldl" >> $F_MAKE
elif [ "$1" = "ptd" ]
then
	echo "CFLAGS= -pthread" >> $F_MAKE
fi

echo "default:" >> $F_MAKE

for i in $SRC_LIST
do
	if [ "$1" = "sql" ]
	then
		echo -e "\tgcc -o $i \$(CFLAGS) $i.c \$(LIBS)" >> $F_MAKE
	elif [ "$1" = "ptd" ]
	then
		echo -e "\tgcc -o $i \$(CFLAGS) $i.c" >> $F_MAKE
	else
		echo -e "\tgcc -o $i $i.c" >> $F_MAKE
	fi
done

echo "clean:" >> $F_MAKE
echo -e -n "\trm " >> $F_MAKE

for i in $SRC_LIST
do
	echo -n "$i " >> $F_MAKE
done

echo >> $F_MAKE
