#!/bin/bash
SRC_FILE_LIST=`ls | grep "\.c$"`
F_MAKE=Makefile
DATA=tmp.dat

for i in $SRC_FILE_LIST
do
	echo $i >> "$DATA"
done

if [ "$1" = "sql" ]
then
	echo "CFLAGS= -I/usr/include/mysql" > $F_MAKE
	echo "LIBS= -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -latomic -ldl" >> $F_MAKE
	echo "default:" >> $F_MAKE
else
	echo "default:" > $F_MAKE
fi

while IFS='.' read -r f1 f2
do
	if [ "$1" = "test" ]
	then
		echo -e "\tgcc -o $f1 \$(CFLAGS) $f1.c \$(LIBS)" >> $F_MAKE
	else
		echo -e "\tgcc -o $f1 $f1.c" >> $F_MAKE
	fi
done < "$DATA"
echo "clean:" >> $F_MAKE
echo -e -n "\trm " >> $F_MAKE
while IFS='.' read -r f1 f2
do
	echo -n "$f1 " >> $F_MAKE
done < "$DATA"
echo >> $F_MAKE

rm $DATA
