default:
	gcc -o getgrnam getgrnam.c
	gcc -o getspnam getspnam.c
	gcc -o getuid getuid.c
	gcc -o pathconf pathconf.c
	gcc -o prac prac.c
	gcc -o pwuid pwuid.c
	gcc -o sysconf sysconf.c
	gcc -o uname uname.c
	gcc -o utmpx utmpx.c
clean:
	rm getgrnam getspnam getuid pathconf prac pwuid sysconf uname utmpx 
