default:
	gcc -o fget_1 fget_1.c
	gcc -o f_rw f_readwrite.c
	gcc -o fprintf_ex fprintf_ex.c
	gcc -o fseek_ex fseek_ex.c
clean:
	rm fget_1 f_rw fprintf_ex fseek_ex

fget_1: fget_1.c
f_rw: f_readwrite.c
fprintf_ex: fprintf_ex.c
fseek_ex: fseek_ex.c
