default:
	gcc -o mqueue_rcv mqueue_rcv.c
	gcc -o mqueue_snd mqueue_snd.c
	gcc -o msq_clnt msq_clnt.c
	gcc -o msq_del msq_del.c
	gcc -o msq_srvr msq_srvr.c
	gcc -o pipe pipe.c
	gcc -o pipe_pair pipe_pair.c
clean:
	rm mqueue_rcv mqueue_snd msq_clnt msq_del msq_srvr pipe pipe_pair 
