default:
	gcc -o fork_exec fork_exec.c
	gcc -o fork_exit fork_exit.c
	gcc -o fork_prac fork_prac.c
	gcc -o fork_prac2 fork_prac2.c
	gcc -o vfork vfork.c
	gcc -o vfork2 vfork2.c

clean:
	rm fork_exec fork_exit fork_prac fork_prac2 vfork vfork2
