default:
	gcc -o file_access file_access.c
	gcc -o inode_stat inode_stat.c
	gcc -o file_type file_type.c
	gcc -o file_macro file_macro.c
	gcc -o dir_detail dir_detail.c
	gcc -o file_link file_link.c
	gcc -o dir_offset dir_offset.c
	gcc -o sym_link sym_link.c
	gcc -o uname uname.c
	gcc -o sys_info sys_info.c
#	gcc -o sys_info2 sys_info2.c
clean:
	rm inode_stat file_type file_macro dir_detail dir_offset file_access file_link sym_link uname sys_info sys_info2
